"""Generated by tools/render_plugin_assets.py. Do not edit."""

CORE_VERSION = "0.6.8"
MCP_REQUIREMENT = "memtomem[onnx]==0.6.8"
TOOL_MODE = "core"
LAUNCH_ENV = {"MEMTOMEM_TOOL_MODE": "core", "ORT_DISABLE_TELEMETRY": "1"}
