"""Authored fictional policy history. Generation inputs, never indexed as evidence."""

# key, label, current, previous, argument, expression, accepted, rejected,
# rationale, incident symptom, operator action, next-work item
DOMAINS = {
    "auth": (
        "인증",
        [
            (
                "legacy_callback",
                "legacy callback",
                True,
                False,
                "legacy_client",
                "legacy_client and config['legacy_callback']['value']",
                True,
                False,
                "데스크톱 2.8 클라이언트가 /api/auth/legacy-callback을 계속 호출한다. AUTH_CALLBACK_V2_ENABLED만으로 구형 경로를 제거하면 재로그인이 불가능하다.",
                "INC-AUTH-17에서 신규 웹 로그인은 정상인데 구형 데스크톱만 callback 404가 발생했다. 웹 성공률 대시보드에는 장애가 드러나지 않았다.",
                "구형 클라이언트 cohort의 callback 404를 확인하고 legacy route를 유지한다. V2 문제는 AUTH_CALLBACK_V2_ENABLED를 false로 되돌려 분리한다.",
                "TASK-AUTH-42: 데스크톱 cohort별 사용량 관찰을 추가한다. 삭제 PR은 아직 승인되지 않았다.",
            ),
            (
                "session_minutes",
                "session expiry",
                60,
                120,
                "age_minutes",
                "age_minutes < config['session_minutes']['value']",
                30,
                90,
                "공용 단말에서 열린 세션이 다음 교대조까지 남지 않게 한다. 개인 기기의 refresh token 정책과 혼동하지 않는다.",
                "교대 종료 후 같은 브라우저를 쓰던 다른 직원에게 이전 tenant 화면이 노출됐다.",
                "idle 시간과 전체 세션 나이를 각각 확인하고 만료 시 재인증한다.",
                "TASK-AUTH-43: session age 경계값을 프런트 안내 문구와 맞춘다.",
            ),
            (
                "login_attempts",
                "login throttle",
                5,
                10,
                "attempts",
                "attempts < config['login_attempts']['value']",
                2,
                8,
                "계정 단위 공격을 늦추되 회사 NAT 뒤의 다른 사용자를 함께 차단하지 않는다.",
                "계정당 10회를 허용하는 동안 자동화 도구가 유효 계정 목록을 추려냈고, "
                "IP 단위로 막자 같은 사무실의 정상 로그인까지 함께 차단됐다.",
                "계정과 시간창을 함께 확인하고 IP 전체 차단을 피한다.",
                "TASK-AUTH-44: 계정별 throttle 로그에 원인 코드를 추가한다.",
            ),
            (
                "invite_hours",
                "invite validity",
                48,
                168,
                "age_hours",
                "age_hours < config['invite_hours']['value']",
                12,
                72,
                "전달된 오래된 초대 링크가 조직 변경 이후 재사용되지 않게 한다.",
                "회수된 초대 메일의 링크가 일주일 뒤에도 사용됐다.",
                "초대 생성 시각과 회수 여부를 조회한 뒤 새 초대를 발급한다.",
                "TASK-AUTH-45: 만료와 회수 상태를 초대 화면에서 구분한다.",
            ),
            (
                "clock_skew_seconds",
                "clock skew",
                30,
                120,
                "offset_seconds",
                "abs(offset_seconds) <= config['clock_skew_seconds']['value']",
                10,
                90,
                "작은 시계 오차는 허용하지만 지나친 허용폭으로 만료 검증을 무력화하지 않는다.",
                "시간 동기화가 끊긴 worker가 만료된 세션을 허용했다.",
                "서버 시간 편차를 측정하고 NTP 복구 후 인증 오류를 재확인한다.",
                "TASK-AUTH-46: 시계 편차 경보를 readiness와 분리한다.",
            ),
            (
                "recovery_codes",
                "recovery inventory",
                8,
                4,
                "remaining",
                "remaining > 0 and remaining <= config['recovery_codes']['value']",
                3,
                0,
                "복구 코드는 한 번만 쓰며 재발급 시 기존 묶음을 모두 폐기한다. "
                "한 묶음은 8개로 발급해 소진으로 인한 잠금을 줄인다.",
                "복구 코드 4개를 모두 소진한 사용자가 재발급 전까지 로그인하지 못해 "
                "지원팀 수동 처리로 몰렸다.",
                "남은 코드 수 분포와 재발급 요청 건수를 함께 확인한다. "
                "소진이 가까운 사용자에게 재발급을 먼저 안내한다.",
                "TASK-AUTH-47: 남은 코드 수가 임계값 아래로 내려가면 재발급을 "
                "안내하는 경고를 추가한다.",
            ),
        ],
    ),
    "billing": (
        "결제",
        [
            (
                "webhook_attempts",
                "billing webhook retry",
                3,
                7,
                "attempts",
                "attempts < config['webhook_attempts']['value']",
                1,
                5,
                "결제 webhook 재전송은 idempotency key로 중복 청구를 막는다. 알림 worker의 5회 재시도 정책을 복사하면 안 된다.",
                "INC-BILL-09에서 공급자 timeout 뒤 재전송을 신규 청구로 처리해 중복 원장이 생겼다.",
                "provider event ID로 중복 수신을 확인하고 settlement 상태가 불명확하면 조회부터 한다.",
                "TASK-BILL-21: 중복 수신 계수와 실제 청구 계수를 분리한다.",
            ),
            (
                "invoice_days",
                "invoice grace period",
                14,
                7,
                "overdue_days",
                "overdue_days <= config['invoice_days']['value']",
                10,
                20,
                "기업 고객의 월말 승인 주기를 반영하되 유예 기간 이후에는 쓰기 기능을 제한한다.",
                "휴일에 청구서가 승인되지 않아 정상 조직이 읽기조차 못 했다.",
                "계약상 유예 일수와 invoice 발행일을 대조하고 읽기 접근은 유지한다.",
                "TASK-BILL-22: 유예 종료 예고 메일에 실제 청구서 링크를 넣는다.",
            ),
            (
                "refund_days",
                "refund eligibility",
                30,
                60,
                "purchase_age_days",
                "purchase_age_days <= config['refund_days']['value']",
                15,
                45,
                "사용량 정산이 닫힌 기간의 환불은 자동 경로 대신 수동 검토로 보낸다.",
                "정산 종료 뒤 자동 환불이 실행돼 보고서 잔액과 공급자 잔액이 달라졌다.",
                "구매 시점과 정산 배치를 확인하고 수동 조정 번호를 남긴다.",
                "TASK-BILL-23: 경계일 테스트에 월말 구매를 추가한다.",
            ),
            (
                "seat_floor",
                "minimum seats",
                3,
                1,
                "seats",
                "seats >= config['seat_floor']['value']",
                5,
                1,
                "팀 요금제 최소 좌석은 3석이다. 개인 무료 요금제에는 이 정책을 적용하지 않는다.",
                "팀 요금제 계정이 좌석 1석까지 내려간 채 팀 기능을 계속 쓰면서 "
                "개인 요금제 기준 견적을 받았다.",
                "요금제 유형을 먼저 확인하고 견적과 실제 청구에 같은 좌석 기준을 사용한다.",
                "TASK-BILL-24: downgrade 경로의 견적 검사를 연결한다.",
            ),
            (
                "reconcile_minutes",
                "settlement lag",
                20,
                5,
                "lag_minutes",
                "lag_minutes <= config['reconcile_minutes']['value']",
                10,
                40,
                "공급자의 지연 이벤트를 기다린 후 불일치 경보를 낸다. 결제 성공 여부를 임의로 바꾸지 않는다.",
                "짧은 경보 창으로 정상 지연 건마다 재정산 요청이 생성됐다.",
                "공급자 event 시각과 수신 시각을 비교하고 지연 건은 다음 배치에서 재조회한다.",
                "TASK-BILL-25: 지연과 영구 누락을 다른 큐로 보낸다.",
            ),
            (
                "currency_scale",
                "currency precision",
                2,
                4,
                "decimal_places",
                "decimal_places <= config['currency_scale']['value']",
                2,
                3,
                "이 합성 USD 요금제는 소수 둘째 자리까지 받는다. 다른 통화로 일반화하지 않는다.",
                "부동소수점 변환 후 공급자 요청과 로컬 원장 합계가 달라졌다.",
                "최소 통화 단위의 정수로 대조하고 입력 precision 초과를 거절한다.",
                "TASK-BILL-26: Decimal 변환 경로를 견적 UI와 공유한다.",
            ),
        ],
    ),
    "notifications": (
        "알림",
        [
            (
                "retry_attempts",
                "notification retry policy",
                5,
                12,
                "attempts",
                "attempts < config['retry_attempts']['value']",
                4,
                6,
                "알림 retry policy는 최대 5회, 250 ms backoff와 jitter다. 수신자에게 중복 메일을 보내지 않도록 delivery key를 유지한다.",
                "INC-NOTIFY-31에서 공급자 429 이후 12회 즉시 재시도가 retry storm을 만들었다. 결제 webhook의 3회 제한과는 별도 정책이다.",
                "retry queue 깊이와 429 비율을 확인한다. 전송은 잠시 늦추되 delivery key를 새로 만들지 않는다.",
                "TASK-NOTIFY-57: jitter 분포와 delivery key 유지 테스트를 추가한다. retries를 다시 12로 올리지 않는다.",
            ),
            (
                "backoff_ms",
                "notification backoff",
                250,
                50,
                "delay_ms",
                "delay_ms >= config['backoff_ms']['value']",
                300,
                100,
                "재시도 최소 대기 250 ms 위에 jitter를 더해 worker들의 동시 재진입을 분산한다.",
                "같은 시각에 깨어난 worker들이 공급자 quota를 다시 소진했다.",
                "실제 대기 히스토그램을 보고 동일 간격에 요청이 몰리는지 확인한다.",
                "TASK-NOTIFY-58: seed를 고정한 jitter 단위 테스트를 넣는다.",
            ),
            (
                "batch_size",
                "digest batch",
                40,
                100,
                "recipients",
                "recipients <= config['batch_size']['value']",
                20,
                70,
                "digest 묶음을 줄여 특정 tenant의 대량 전송이 나머지 알림을 막지 않게 한다.",
                "주간 digest가 실시간 초대 메일보다 먼저 큐를 독점했다.",
                "tenant별 대기 시간을 확인하고 digest와 실시간 전송을 별도 큐로 분리한다.",
                "TASK-NOTIFY-59: 공정성 테스트에 대형 tenant를 추가한다.",
            ),
            (
                "dedupe_hours",
                "delivery deduplication",
                24,
                6,
                "age_hours",
                "age_hours < config['dedupe_hours']['value']",
                12,
                30,
                "하루 이내 같은 delivery key는 재전송 결과를 재사용한다. 새 사용자 행동은 새 key를 쓴다.",
                "공급자 응답 유실 뒤 늦게 재시도한 알림이 두 번 배달됐다.",
                "전송 이력의 key와 TTL을 조회하고 이미 성공한 응답을 반환한다.",
                "TASK-NOTIFY-60: TTL 경계의 이중 전송 검사를 추가한다.",
            ),
            (
                "payload_kb",
                "email payload",
                128,
                256,
                "size_kb",
                "size_kb <= config['payload_kb']['value']",
                64,
                200,
                "큰 첨부물은 본문 대신 파일 링크로 전달한다. 파일 권한은 수신 시점에 다시 검사한다.",
                "인라인 이미지가 메일 공급자 크기 제한을 넘어 전체 batch가 거절됐다.",
                "렌더링 후 payload 크기를 측정하고 링크 전환 후 다시 요청한다.",
                "TASK-NOTIFY-61: 멀티바이트 본문의 byte 길이를 측정한다.",
            ),
            (
                "queue_age_minutes",
                "notification queue age",
                15,
                60,
                "age_minutes",
                "age_minutes <= config['queue_age_minutes']['value']",
                5,
                25,
                "초대·멘션 알림의 지연은 큐 길이보다 가장 오래된 메시지 나이로 감지한다.",
                "낮은 처리량의 tenant 큐가 작아도 오래 대기하는데 경보가 없었다.",
                "가장 오래된 event 시각을 확인하고 poison message를 격리한다.",
                "TASK-NOTIFY-62: dead-letter 이동 이유를 인계 화면에 노출한다.",
            ),
        ],
    ),
    "jobs": (
        "백그라운드 작업",
        [
            (
                "lease_seconds",
                "worker lease recovery",
                90,
                30,
                "heartbeat_age",
                "heartbeat_age < config['lease_seconds']['value']",
                40,
                120,
                "worker lease는 90초이며 완료 체크포인트를 먼저 확인한 후 재할당한다. timeout만 보고 같은 작업을 두 번 시작하지 않는다.",
                "INC-JOBS-22에서 GC pause로 heartbeat가 늦자 살아 있는 worker의 작업을 다른 worker가 다시 수행했다.",
                "checkpoint와 lease owner를 함께 읽는다. 완료면 결과를 재사용하고 만료·미완료일 때만 다시 claim한다.",
                "TASK-JOBS-88: worker 재시작 뒤 완료 checkpoint를 읽는 경로부터 확인한다. 신규 작업 제출은 보류한다.",
            ),
            (
                "max_parallel",
                "worker concurrency",
                4,
                16,
                "running",
                "running < config['max_parallel']['value']",
                2,
                8,
                "CPU 작업 4개를 넘기지 않아 heartbeat 스레드가 굶지 않게 한다.",
                "과도한 병렬 압축이 이벤트 루프를 막아 lease가 연달아 만료됐다.",
                "CPU와 heartbeat 지연을 함께 보고 동시 작업 수를 낮춘다.",
                "TASK-JOBS-89: 부하 테스트에 heartbeat deadline을 기록한다.",
            ),
            (
                "checkpoint_seconds",
                "checkpoint interval",
                20,
                60,
                "elapsed_seconds",
                "elapsed_seconds >= config['checkpoint_seconds']['value']",
                30,
                10,
                "20초마다 재개 가능한 offset을 기록한다. 부분 파일이 durable해진 뒤에만 offset을 전진시킨다.",
                "메모리상의 진행률만 저장해 재시작 후 누락된 출력 구간이 생겼다.",
                "출력 flush와 checkpoint 순서를 확인하고 마지막 durable offset부터 재개한다.",
                "TASK-JOBS-90: 강제 종료 지점을 바꿔 재개 테스트를 반복한다.",
            ),
            (
                "retry_budget",
                "job retry budget",
                2,
                6,
                "attempts",
                "attempts < config['retry_budget']['value']",
                1,
                4,
                "같은 입력으로 계속 실패하는 CPU 작업은 두 번 뒤 검토 큐로 보낸다. 알림 retry와 다른 예산이다.",
                "손상된 파일 하나가 worker 시간을 반복 소비하며 정상 작업을 밀어냈다.",
                "입력 checksum과 실패 원인이 같은지 확인하고 재현 자료를 격리한다.",
                "TASK-JOBS-91: permanent 오류 분류를 검토한다.",
            ),
            (
                "shutdown_seconds",
                "worker shutdown grace",
                45,
                10,
                "elapsed_seconds",
                "elapsed_seconds <= config['shutdown_seconds']['value']",
                20,
                60,
                "종료 요청 뒤 새 claim은 막고 진행 중인 작업의 마지막 checkpoint에 시간을 준다.",
                "즉시 종료 때문에 결과는 썼지만 완료 표시가 없어 작업이 다시 실행됐다.",
                "draining 상태와 마지막 checkpoint를 확인한 뒤 프로세스를 종료한다.",
                "TASK-JOBS-92: 배포 스크립트의 grace 값과 맞춘다.",
            ),
            (
                "backlog_limit",
                "job admission",
                200,
                1000,
                "queued",
                "queued < config['backlog_limit']['value']",
                100,
                300,
                "처리 용량을 넘는 작업은 접수 시 재시도 가능한 응답을 준다. 대기열을 무한히 늘리지 않는다.",
                "대량 업로드가 오래된 작업의 처리 약속을 깨뜨렸다.",
                "tenant별 입장 제한을 확인하고 예약 작업의 backpressure를 켠다.",
                "TASK-JOBS-93: 응답의 retry-after 안내를 추가한다.",
            ),
        ],
    ),
    "files": (
        "파일 관리",
        [
            (
                "upload_mb",
                "file upload limit",
                25,
                100,
                "size_mb",
                "size_mb <= config['upload_mb']['value']",
                10,
                50,
                "동기 업로드는 25 MB까지 받는다. 큰 파일은 multipart 경로로 보내 worker 메모리를 보호한다.",
                "INC-FILES-12에서 동시 대형 업로드가 작은 첨부 요청까지 OOM으로 실패시켰다.",
                "content length와 실제 수신량을 비교하고 multipart upload 상태를 조회한다.",
                "TASK-FILES-33: 중단된 multipart session의 정리 작업을 추가한다.",
            ),
            (
                "signed_url_minutes",
                "signed URL lifetime",
                10,
                60,
                "age_minutes",
                "age_minutes < config['signed_url_minutes']['value']",
                5,
                20,
                "다운로드 링크의 수명을 짧게 유지하고 재발급 때 파일 접근 권한을 다시 확인한다.",
                "외부로 전달된 링크가 공유 해제 뒤에도 오래 동작했다.",
                "링크 발급 시각과 공유 해제 시각을 비교하고 신규 URL 발급을 중단한다.",
                "TASK-FILES-34: 만료 응답에서 로그인 이동 경로를 확인한다.",
            ),
            (
                "retention_days",
                "trash retention",
                30,
                7,
                "deleted_days",
                "deleted_days <= config['retention_days']['value']",
                14,
                40,
                "휴지통은 30일간 복원 가능하다. 법적 보존 요청이 있는 파일은 별도 hold로 관리한다.",
                "실수 삭제를 일주일 뒤 발견해 복구 기간을 놓친 조직이 있었다.",
                "삭제 표시와 실제 blob 존재를 확인하고 hold 여부부터 조회한다.",
                "TASK-FILES-35: 복원 시 원래 폴더가 없을 때의 동작을 정한다.",
            ),
            (
                "scan_seconds",
                "malware scan timeout",
                120,
                30,
                "elapsed_seconds",
                "elapsed_seconds <= config['scan_seconds']['value']",
                60,
                180,
                "스캔 timeout은 안전 판정이 아니다. 결과가 없으면 다운로드를 계속 보류한다.",
                "timeout을 clean으로 취급한 경로 때문에 검사가 끝나지 않은 파일이 공개됐다.",
                "scan 상태가 pending인지 확인하고 재검사 큐로 보낸다.",
                "TASK-FILES-36: unknown 상태를 UI에서 별도로 표시한다.",
            ),
            (
                "preview_pages",
                "document preview",
                20,
                100,
                "pages",
                "pages <= config['preview_pages']['value']",
                10,
                30,
                "첫 미리보기는 20쪽으로 제한하고 전체 변환은 비동기 요청으로 분리한다.",
                "긴 PDF 한 개가 preview worker를 점유해 이미지 썸네일까지 지연됐다.",
                "쪽 수와 preview job 종류를 확인하고 대형 변환을 별도 큐로 보낸다.",
                "TASK-FILES-37: preview 제한 안내에 원본 다운로드를 연결한다.",
            ),
            (
                "chunk_mb",
                "multipart chunk",
                8,
                32,
                "part_mb",
                "part_mb <= config['chunk_mb']['value']",
                4,
                16,
                "이 데모의 multipart 조각은 최대 8 MB다. 전체 파일 크기 제한과 같은 값이 아니다.",
                "큰 조각 재전송이 느린 네트워크에서 계속 timeout됐다.",
                "실패한 part 번호와 checksum을 확인하고 해당 조각만 재전송한다.",
                "TASK-FILES-38: 중복 part 완료 이벤트를 idempotent하게 처리한다.",
            ),
        ],
    ),
    "reports": (
        "리포트",
        [
            (
                "freshness_minutes",
                "report freshness",
                15,
                60,
                "age_minutes",
                "age_minutes <= config['freshness_minutes']['value']",
                10,
                30,
                "리포트는 최대 15분 지연을 허용하며 기준 시각을 화면에 표시한다. 결제 원장의 실시간 진실로 쓰지 않는다.",
                "INC-REPORT-08에서 어제 생성된 캐시가 최신 매출처럼 표시돼 운영자가 정산을 다시 요청했다.",
                "materialized_at과 원장 event watermark를 비교한다. 갱신 실패 시 이전 값과 지연 상태를 함께 보여준다.",
                "TASK-REPORT-19: 새 thread에서는 캐시 시각과 마지막 성공 배치부터 확인한다.",
            ),
            (
                "export_rows",
                "CSV export rows",
                10000,
                50000,
                "rows",
                "rows <= config['export_rows']['value']",
                5000,
                20000,
                "동기 CSV는 1만 행까지이고 큰 내보내기는 job ID를 반환한다.",
                "동기 요청 timeout 뒤 사용자가 다시 눌러 같은 export가 여러 번 만들어졌다.",
                "export 요청 ID로 기존 job을 조회하고 중복 클릭에는 같은 ID를 반환한다.",
                "TASK-REPORT-20: job 완료 알림에 재다운로드 링크를 넣는다.",
            ),
            (
                "window_days",
                "report window",
                90,
                365,
                "days",
                "days <= config['window_days']['value']",
                30,
                180,
                "대화형 조회는 90일 창으로 제한한다. 장기 감사 자료는 별도 batch export로 제공한다.",
                "1년 범위의 조인 쿼리가 운영 DB의 온라인 트래픽을 밀어냈다.",
                "요청 기간을 확인하고 읽기 전용 분석 경로로 우회한다.",
                "TASK-REPORT-21: 기간 초과 안내에 비동기 export를 제안한다.",
            ),
            (
                "cache_seconds",
                "report cache ttl",
                300,
                1800,
                "age_seconds",
                "age_seconds < config['cache_seconds']['value']",
                100,
                600,
                "동일 조건 리포트는 5분간 재사용한다. tenant와 권한 버전이 cache key에 포함된다.",
                "권한 변경 뒤에도 오래된 cache가 보였고 조직 구분이 빠진 key가 발견됐다.",
                "cache key의 tenant와 permission revision을 확인하고 영향을 받은 key만 무효화한다.",
                "TASK-REPORT-22: 권한 축소 후 cache 접근 테스트를 추가한다.",
            ),
            (
                "minimum_group",
                "aggregate group privacy",
                5,
                1,
                "members",
                "members >= config['minimum_group']['value']",
                8,
                2,
                "이 데모의 집계는 5명 미만 그룹을 숨긴다. 개인정보 보호의 일반적인 충분조건으로 해석하지 않는다.",
                "한 명뿐인 팀의 통계가 개인 활동 내역처럼 표시됐다.",
                "그룹 크기를 확인하고 작은 그룹은 상위 집계로 합친다.",
                "TASK-REPORT-23: 교차 필터로 작은 그룹이 드러나는지 검토한다.",
            ),
            (
                "query_seconds",
                "report query timeout",
                8,
                30,
                "elapsed_seconds",
                "elapsed_seconds <= config['query_seconds']['value']",
                4,
                15,
                "느린 조회는 8초에 중단하고 비동기 분석을 안내한다. timeout을 빈 데이터로 표시하지 않는다.",
                "30초까지 실행되는 조회가 운영 DB 커넥션을 오래 점유해 "
                "같은 시각의 다른 리포트 요청까지 함께 느려졌다.",
                "query 상태와 오류 코드를 확인하고 마지막 정상 결과와 구분해서 표시한다.",
                "TASK-REPORT-24: empty와 failed 상태의 화면 테스트를 추가한다.",
            ),
        ],
    ),
}

FIELDS = "key label current previous argument expression accepted rejected rationale symptom action next_work".split()


def domains():
    for slug, (label, rows) in DOMAINS.items():
        yield slug, label, [dict(zip(FIELDS, row, strict=True)) for row in rows]
