#!/usr/bin/env python3
"""Validate reviewed OSV exceptions and emit OSV Scanner native TOML."""

from __future__ import annotations

import argparse
import datetime as dt
import json
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Any


DEFAULT_INPUT = Path(__file__).with_name("osv-exceptions.toml")
_REQUIRED_KEYS = {"id", "owner", "reason", "ignoreUntil"}


class ExceptionConfigError(ValueError):
    """The reviewed exception configuration is unsafe or malformed."""


@dataclass(frozen=True)
class OsvException:
    id: str
    owner: str
    reason: str
    ignore_until: dt.date


def _single_line_string(raw: dict[str, Any], key: str, index: int) -> str:
    value = raw.get(key)
    if not isinstance(value, str) or not value.strip():
        raise ExceptionConfigError(f"exceptions[{index}].{key} must be a non-empty string")
    value = value.strip()
    if "\n" in value or "\r" in value:
        raise ExceptionConfigError(f"exceptions[{index}].{key} must be a single-line string")
    return value


def load_exceptions(path: Path, *, today: dt.date | None = None) -> list[OsvException]:
    """Load the canonical schema, rejecting unknown keys and expired entries."""
    today = today or dt.datetime.now(dt.timezone.utc).date()
    try:
        payload = tomllib.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, tomllib.TOMLDecodeError) as exc:
        raise ExceptionConfigError(f"cannot read valid TOML from {path}: {exc}") from exc
    unknown_top = set(payload) - {"exceptions"}
    if unknown_top:
        raise ExceptionConfigError(f"unknown top-level keys: {sorted(unknown_top)}")
    rows = payload.get("exceptions", [])
    if not isinstance(rows, list):
        raise ExceptionConfigError("exceptions must be an array of tables")
    result: list[OsvException] = []
    seen: set[str] = set()
    for index, raw in enumerate(rows):
        if not isinstance(raw, dict):
            raise ExceptionConfigError(f"exceptions[{index}] must be a table")
        keys = set(raw)
        if keys != _REQUIRED_KEYS:
            missing, extra = _REQUIRED_KEYS - keys, keys - _REQUIRED_KEYS
            raise ExceptionConfigError(
                f"exceptions[{index}] schema mismatch; missing={sorted(missing)}, extra={sorted(extra)}"
            )
        advisory_id = _single_line_string(raw, "id", index)
        owner = _single_line_string(raw, "owner", index)
        reason = _single_line_string(raw, "reason", index)
        ignore_until = raw["ignoreUntil"]
        if isinstance(ignore_until, dt.datetime) or not isinstance(ignore_until, dt.date):
            raise ExceptionConfigError(
                f"exceptions[{index}].ignoreUntil must be a bare TOML YYYY-MM-DD date"
            )
        if ignore_until <= today:
            raise ExceptionConfigError(
                f"exceptions[{index}] {advisory_id} expired on {ignore_until.isoformat()}"
            )
        if advisory_id in seen:
            raise ExceptionConfigError(f"duplicate OSV exception id: {advisory_id}")
        seen.add(advisory_id)
        result.append(OsvException(advisory_id, owner, reason, ignore_until))
    return result


def render_native(exceptions: list[OsvException]) -> str:
    """Render only keys accepted by OSV Scanner v2's strict config parser."""
    lines = ["# Generated by tools/check_osv_exceptions.py; do not edit."]
    for entry in exceptions:
        lines.extend(
            [
                "",
                f"# reviewed owner: {entry.owner}",
                "[[IgnoredVulns]]",
                f"id = {json.dumps(entry.id)}",
                f"reason = {json.dumps(entry.reason)}",
                f"ignoreUntil = {entry.ignore_until.isoformat()}",
            ]
        )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args(argv)
    try:
        exceptions = load_exceptions(args.input)
        args.output.write_text(render_native(exceptions), encoding="utf-8")
    except (OSError, UnicodeError, ExceptionConfigError) as exc:
        print(f"OSV exception validation failed: {exc}", file=sys.stderr)
        return 1
    print(f"validated {len(exceptions)} OSV exception(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
