#!/usr/bin/env python3
"""Render the shipped Claude, Codex, and OpenCode assets from one contract."""

from __future__ import annotations

import argparse
import json
import sys
import tomllib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "packages" / "memtomem-plugin-assets"
CONTRACT = ASSETS / "contract.toml"
CLAUDE_ROOT = ROOT / "packages" / "memtomem-claude-plugin"
CODEX_ROOT = ROOT / "plugins" / "memtomem"
OPENCODE_ROOT = ROOT / "packages" / "opencode-memtomem"


def _q(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _yaml_q(value: str) -> str:
    return _q(value)


def _allowed_tools(tools: list[str]) -> str:
    names: list[str] = []
    for tool in tools:
        names.extend(
            [
                f"mcp__plugin_memtomem_memtomem__{tool}",
                f"mcp__memtomem__{tool}",
            ]
        )
    return ", ".join(names)


def _claude_skill(workflow: dict, body: str) -> str:
    frontmatter = [
        "---",
        f"name: {workflow['id']}",
        f"description: {workflow['description']}",
    ]
    if hint := workflow.get("argument_hint"):
        frontmatter.append(f"argument-hint: {hint}")
    frontmatter.append(f"allowed-tools: {_allowed_tools(workflow['tools'])}")
    if not workflow["implicit"]:
        frontmatter.append("disable-model-invocation: true")
    frontmatter.extend(["---", "", f"# {workflow['title']}", ""])
    if workflow["id"] != "status":
        frontmatter.extend(
            [
                f"Use `$ARGUMENTS` as the {workflow['input_kind']}.",
                f"If the request does not clearly specify the {workflow['input_kind']}, ask before calling a tool.",
                "",
            ]
        )
    return "\n".join(frontmatter) + body.strip() + "\n"


def _codex_skill(workflow: dict, body: str) -> str:
    lines = [
        "---",
        f"name: {workflow['codex_name']}",
        f"description: {workflow['description']}",
        "---",
        "",
        f"# {workflow['title']}",
        "",
    ]
    if workflow["id"] != "status":
        lines.extend(
            [
                f"Derive the {workflow['input_kind']} from the current user request.",
                f"If the request does not clearly specify the {workflow['input_kind']}, ask before calling a tool.",
                "",
            ]
        )
    return "\n".join(lines) + body.strip() + "\n"


def _openai_yaml(workflow: dict) -> str:
    implicit = "true" if workflow["implicit"] else "false"
    return (
        "interface:\n"
        f"  display_name: {_yaml_q(workflow['ui_name'])}\n"
        f"  short_description: {_yaml_q(workflow['ui_description'])}\n"
        f"  default_prompt: {_yaml_q(workflow['default_prompt'])}\n"
        "policy:\n"
        f"  allow_implicit_invocation: {implicit}\n"
    )


def _opencode_body(body: str, tools: list[str]) -> str:
    for tool in tools:
        body = body.replace(f"`{tool}`", f"`memtomem_{tool}`")
    return body


def _opencode_skill(workflow: dict, body: str, version_range: str) -> str:
    lines = [
        "---",
        f"name: {workflow['codex_name']}",
        f"description: {workflow['description']}",
        "license: Apache-2.0",
        f"compatibility: OpenCode {version_range}",
        "metadata:",
        "  provider: memtomem",
        "---",
        "",
        f"# {workflow['title']}",
        "",
    ]
    if workflow["id"] != "status":
        lines.extend(
            [
                f"Derive the {workflow['input_kind']} from the current user request.",
                f"If the request does not clearly specify the {workflow['input_kind']}, ask before calling a tool.",
                "",
            ]
        )
    return "\n".join(lines) + _opencode_body(body, workflow["tools"]).strip() + "\n"


def _opencode_generated(contract: dict) -> str:
    commands = {}
    for workflow in contract["workflows"]:
        body = (ASSETS / "workflows" / f"{workflow['id']}.md").read_text(encoding="utf-8")
        prompt = _opencode_body(body, workflow["tools"]).strip()
        prefix = f"Use the memtomem {workflow['id']} workflow."
        if workflow["id"] != "status":
            prompt = f"{prefix}\n\nUser input: $ARGUMENTS\n\n{prompt}"
        else:
            prompt = f"{prefix}\n\n{prompt}"
        commands[f"memtomem-{workflow['id']}"] = {
            "description": workflow["description"],
            "template": prompt,
        }
    payload = json.dumps(commands, indent=2, ensure_ascii=False)
    core = contract["core"]
    opencode = contract["opencode"]
    return (
        "// Generated by tools/render_plugin_assets.py. Do not edit.\n"
        f"export const CORE_VERSION = {_q(core['version'])};\n"
        f"export const TOOL_MODE = {_q(core['tool_mode'])};\n"
        f"export const MCP_TIMEOUT_MS = {opencode['mcp_timeout_ms']};\n"
        f"export const OPENCODE_COMMANDS = {payload} as const;\n"
        "export const OPENCODE_READ_SKILLS = [\n"
        + "".join(
            f"  {_q(workflow['codex_name'])},\n"
            for workflow in contract["workflows"]
            if workflow["implicit"] and workflow["effect"] == "read"
        )
        + "] as const;\n"
    )


def _mcp_config(core: dict) -> str:
    payload = {
        "mcpServers": {
            "memtomem": {
                "command": "uvx",
                "args": ["--from", f"memtomem=={core['version']}", "memtomem-server"],
                "env": {"MEMTOMEM_TOOL_MODE": core["tool_mode"]},
            }
        }
    }
    return json.dumps(payload, indent=2) + "\n"


def expected_files() -> dict[Path, str]:
    contract = tomllib.loads(CONTRACT.read_text(encoding="utf-8"))
    files: dict[Path, str] = {
        CLAUDE_ROOT / ".mcp.json": _mcp_config(contract["core"]),
        CODEX_ROOT / ".mcp.json": _mcp_config(contract["core"]),
        OPENCODE_ROOT / "src" / "generated.ts": _opencode_generated(contract),
    }
    for workflow in contract["workflows"]:
        body = (ASSETS / "workflows" / f"{workflow['id']}.md").read_text(encoding="utf-8")
        # Optional Claude-only appendix: workflows/<id>.claude.md is appended to the
        # Claude skill body only, so plugin-namespace guidance never leaks into the
        # Codex/OpenCode renders (guarded by test_plugin_assets leak checks).
        claude_body = body
        sidecar = ASSETS / "workflows" / f"{workflow['id']}.claude.md"
        if sidecar.is_file():
            claude_body = body.strip() + "\n\n" + sidecar.read_text(encoding="utf-8")
        files[CLAUDE_ROOT / "skills" / workflow["id"] / "SKILL.md"] = _claude_skill(
            workflow, claude_body
        )
        codex_dir = CODEX_ROOT / "skills" / workflow["codex_name"]
        files[codex_dir / "SKILL.md"] = _codex_skill(workflow, body)
        files[codex_dir / "agents" / "openai.yaml"] = _openai_yaml(workflow)
        if workflow["implicit"] and workflow["effect"] == "read":
            files[OPENCODE_ROOT / "skills" / workflow["codex_name"] / "SKILL.md"] = _opencode_skill(
                workflow, body, contract["opencode"]["version_range"]
            )
    return files


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated files drift")
    args = parser.parse_args()

    drift: list[Path] = []
    for path, content in expected_files().items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                drift.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    if drift:
        for path in drift:
            print(f"drift: {path.relative_to(ROOT)}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
