// Generated by tools/render_plugin_assets.py. Do not edit.
export const CORE_VERSION = "0.3.9";
export const TOOL_MODE = "core";
export const MCP_TIMEOUT_MS = 60000;
export const OPENCODE_COMMANDS = {
  "memtomem-search": {
    "description": "Search indexed memtomem memories by topic. Use for past decisions, notes, findings, or project context that may exist in the memory index.",
    "template": "Use the memtomem search workflow.\n\nUser input: $ARGUMENTS\n\nCall `memtomem_mem_search` with the requested topic and use the compact output unless machine-readable details are necessary.\n\nPresent the strongest matches concisely with their source path, heading, and relevance score. Explain that memtomem uses BM25 by default and adds dense retrieval only when embeddings are configured. If nothing matches, suggest a broader query or the status workflow; do not write or index anything automatically."
  },
  "memtomem-recall": {
    "description": "Recall memtomem memories created in a date range. Use for recent memories or requests scoped by day, week, month, source, or namespace.",
    "template": "Use the memtomem recall workflow.\n\nUser input: $ARGUMENTS\n\nTranslate relative dates such as “last week” into `since` and `until` values when possible, then call `memtomem_mem_recall`. Preserve any source, namespace, scope, or result-limit constraint from the request.\n\nPresent memories newest first with their creation date and source. Ask for a date range only when the request provides no usable temporal constraint. Use topic search, not recall, when the user is asking what a memory says rather than when it was created."
  },
  "memtomem-status": {
    "description": "Check memtomem configuration, storage, index counts, dense coverage, and warnings. Use when search is empty, degraded, or needs diagnosis.",
    "template": "Use the memtomem status workflow.\n\nCall `memtomem_mem_status` once. Report the storage backend and database path, embedding state, source and chunk counts, dense-vector coverage, and warnings that the tool actually returns.\n\nTreat `provider=none` and BM25-only coverage as a supported default, not a failed setup. Do not claim namespace totals or other fields absent from the response."
  },
  "memtomem-remember": {
    "description": "Save an explicit user-requested memory with memtomem. Use only when the user clearly asks to remember, record, or persist information for later.",
    "template": "Use the memtomem remember workflow.\n\nUser input: $ARGUMENTS\n\nConfirm that the user explicitly requested persistence, then call `memtomem_mem_add` with the requested content. Add a natural title and a small set of useful tags only when they are clear from the content.\n\nUse `scope=\"user\"` by default and leave `force_unsafe=false`. Use `project_shared` only after explicit confirmation and set `confirm_project_shared=true`. Report the written file and indexed chunk count. If the tool reports a similar memory, surface the warning rather than silently creating another variant."
  },
  "memtomem-index": {
    "description": "Index or re-index an explicitly selected file or directory with memtomem. Use for initial ingestion or intentional refresh after file changes.",
    "template": "Use the memtomem index workflow.\n\nUser input: $ARGUMENTS\n\nRequire an explicit file or directory path before calling `memtomem_mem_index`; never rely on its `.` default. Resolve ambiguity with the user before indexing a broad directory.\n\nUse `force=false` and `auto_tag=false` unless the user explicitly requests otherwise. Report scanned, indexed, skipped, deleted, and blocked counts. Explain redaction or embedding-mismatch failures without bypassing them automatically."
  },
  "memtomem-setup": {
    "description": "Set up and verify a first memtomem memory source. Use for onboarding, choosing an index path, or confirming that search works.",
    "template": "Use the memtomem setup workflow.\n\nUser input: $ARGUMENTS\n\n1. Call `memtomem_mem_status` and treat the default `provider=none` BM25-only configuration as healthy.\n2. Obtain an explicit notes or memory directory from the request; ask for one when absent.\n3. Call `memtomem_mem_index` on that path with `force=false` and `auto_tag=false`.\n4. Choose a representative phrase from the indexed material and call `memtomem_mem_search` to verify retrieval.\n5. Report the first-success path and mention embeddings only as an optional relevance enhancement.\n\nDo not install Ollama, enable automation hooks, or edit host instruction files unless the user separately requests those actions."
  }
} as const;
export const OPENCODE_READ_SKILLS = [
  "memtomem-search",
  "memtomem-recall",
  "memtomem-status",
] as const;
